# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
weight = 1
name = "GitHub"
url = "https://github.com/SlimeNull"

[social.params]
icon = "social-github"

[[social]]
identifier = "bilibili"
weight = 2
name = "Bilibili"
url = "https://space.bilibili.com/441842015"

[social.params]
icon = "social-bilibili"
